question_data = [{"category": "History", "type": "boolean", "difficulty": "easy",
                  "question": "The Cold War ended with Joseph Stalin's death.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "History", "type": "boolean", "difficulty": "easy",
                  "question": "The Spitfire originated from a racing plane.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "History", "type": "boolean", "difficulty": "easy",
                  "question": "The United States was a member of the League of Nations.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "History", "type": "boolean", "difficulty": "easy",
                  "question": "United States President John F. Kennedy was assassinated during his presidential motorcade in Atlanta, Georgia on November 22nd, 1963.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "History", "type": "boolean", "difficulty": "easy",
                  "question": "Adolf Hitler was a german soldier in World War I.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "History", "type": "boolean", "difficulty": "easy",
                  "question": "In World War ll, Great Britian used inflatable tanks on the ports of Great Britain to divert Hitler away from Normandy\/D-day landing.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "History", "type": "boolean", "difficulty": "easy",
                  "question": "Kublai Khan is the grandchild of Genghis Khan?",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "History", "type": "boolean", "difficulty": "easy",
                  "question": "The French Kingdom helped the United States gain their independence over Great Britain during the Revolutionary War.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "History", "type": "boolean", "difficulty": "easy",
                  "question": "The United States of America was the first country to launch a man into space.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "History", "type": "boolean", "difficulty": "easy",
                  "question": "Thomas Crapper was a plumber who invented the flushing toilet.",
                  "correct_answer": "False", "incorrect_answers": ["True"]}]
